Correction of task 1 and 2

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -2,16 +2,37 @@
 # A script that configures Nginx server to return
 # a header 'X-Served-By'
 
-# config="server {\n\tlisten 80;\n\tserver_name 52.3.255.219;\n\troot /var/www/html;\n\t location / {\n\t\tadd_header X-Served-By \"351953-web-02\";\n\t}"
-
-if [ ! -x /usr/sbin/nginx ]; then
-   apt-get update
-   apt-get install -y nginx
+if ! command -v nginx &> /dev/null; then
+   sudo apt-get update
+   sudo apt-get install nginx -y
 fi
 
-echo -e "server {\n\tlisten 80;\n\tserver_name 52.3.255.219;\
-\n\troot /var/www/html;\n\tindex index.html;\n\
-\n\tlocation / {\n\t\tadd_header X-Served-By \"351953-web-02\";\
-\n\t}\n}" | sudo tee -a /etc/nginx/sites-enabled/default > /dev/null
+static_html_dir="/var/www/static_html"
+if [ ! -d "$static_html_dir" ]; then
+	sudo mkdir -p "$static_html_dir"
+fi
 
-sudo service nginx start
+static_html="$static_html_dir/index.html"
+echo "Hello Everyone" | sudo tee "$static_html" > /dev/null
+
+error_html="$static_html_dir/404.html"
+if [ ! -f "$error_html" ]; then
+	touch "$error_html"
+	echo -e "C'est ne pas une page" | sudo tee "$error_html" > /dev/null
+fi
+
+echo "server {
+	listen 80 default_server;
+	listen [::]:80 default_server;
+	root $static_html_dir;
+	index index.html index.htm;
+	add_header X-Served-By \$HOSTNAME;
+	
+	error_page 404 /404.html;
+	location = /404.html {
+		root $static_html_dir;
+		internal;
+	}
+}" | sudo tee /etc/nginx/sites-available/default > /dev/null
+
+sudo service nginx restart
